name: Zip It

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: ZIP files for chrome
        run: |
          cp chrome_manifest.json manifest.json
          zip chrome_extension_squint.zip manifest.json style.css content.js README.md images/
          rm manifest.json

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: chrome_extension_squint.zip