name: Zip It

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Preparing...
        run: |
          mv style.css style_.css

      - name: ZIP files for chrome
        run: |
          cp style_.css style.css
          cp chrome_manifest.json manifest.json
          zip -r chrome_extension_squint.zip manifest.json style.css content.js README.md images/
          rm manifest.json
          rm style.css

      - name: ZIP files for firefox
        run: |
          cp style_.css style.css
          sed -i 's/chrome-extension/moz-extension/g' style.css
          cp firefox_manifest.json manifest.json
          zip -r firefox_extension_squint.zip manifest.json style.css content.js README.md images/
          rm manifest.json
          rm style.css

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chrome_extension_squint.zip
            firefox_extension_squint.zip